# Generated by Django 2.2.6 on 2022-11-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_type_question',
            name='question',
            field=models.CharField(max_length=1500),
        ),
    ]
