# Generated by Django 2.2.6 on 2023-06-26 04:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_pre_post_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='result_all_question',
            name='comment',
            field=models.CharField(default=-1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='result_all_question',
            name='face_emotion',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
